{% set name = "tiled" %}
{% set version = "0.1.0a77" %}

package:
  name: tiled-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tiled-{{ version }}.tar.gz
  sha256: 6137ac57ef2b70638fdc485b9fe016070f8c21b3fa0cd5d25d348cb8fe73c67b

build:
  number: 0

outputs:
  # Categorized requirements
  - name: tiled-base
    script: build-tiled.sh  # [unix]
    script: bld-tiled.bat  # [win]
    build:
      # TODO: Make noarch when tiled-server is noarch
      entry_points:
        - tiled = tiled.commandline.main:main
    requirements:
      host:
        - appdirs
        - blosc
        - click !=8.1.0
        - dask
        - jsonschema
        - lz4
        - msgpack-python >=1.0.0
        - ndindex
        - numpy
        - pandas
        - pip
        - pyarrow
        - pyarrow
        - python
        - pyyaml
        - sparse >=0.13.0
        - typer
        - xarray
        - zstandard

  - name: tiled-client
    build:
      noarch: generic
    requirements:
      run:
        - entrypoints
        - heapdict
        - {{ pin_subpackage('tiled-base', max_pin='x.x.x') }}
    test:
      imports:
        - tiled
        - tiled.client
        - tiled.client.array
        - tiled.client.base
        - tiled.client.cache
        - tiled.client.constructors
        - tiled.client.context
        - tiled.client.dataframe
        - tiled.client.node
        - tiled.client.sparse
        - tiled.client.utils
        - tiled.client.xarray
      commands:
        - tiled --help

  - name: tiled-server
    requirements:
      host:
        - python
      run:
        - python
        - aiofiles
        - alembic
        - anyio
        - cachey
        # TODO: Can be noarch when Python 3.7 is EOL in June 2023
        - cached-property  # [py<38]
        - cachetools
        - dask
        - fastapi
        - jinja2
        - jmespath
        - orjson
        - packaging
        - psutil
        - prometheus_client
        - pydantic >=1.8.2
        - python-dateutil
        - python-jose
        - python-multipart
        - sqlalchemy
        - starlette
        - toolz
        - uvicorn
        - watchgod
        - {{ pin_subpackage('tiled-base', max_pin='x.x.x') }}
    test:
      imports:
        - tiled
        - tiled.server
        - tiled.server.app
        - tiled.server.authentication
        - tiled.server.compression
        - tiled.server.core
        - tiled.server.dependencies
        - tiled.server.etag
        - tiled.server.object_cache
        - tiled.server.router
        - tiled.server.schemas
        - tiled.server.settings
        - tiled.server.utils
      commands:
        - tiled --help

  - name: tiled-formats
    build:
      noarch: generic
    requirements:
      run:
        - h5py
        - h5netcdf
        - openpyxl
        - pillow
        - tifffile
        - {{ pin_subpackage('tiled-base', max_pin='x.x.x') }}
    test:
      imports:
        - tiled

  # All:
  - name: tiled
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('tiled-client', exact=True) }}
        # tiled-server is the only arch dependant output, so we cannot do exact pinning
        # because there are multiple variants.
        - {{ pin_subpackage('tiled-server', max_pin='x.x.x') }}
        - {{ pin_subpackage('tiled-formats', exact=True) }}
    test:
      imports:
        - tiled
        - tiled.adapters
        - tiled.adapters.array
        - tiled.adapters.dataframe
        - tiled.adapters.excel
        - tiled.adapters.files
        - tiled.adapters.hdf5
        - tiled.adapters.mapping
        - tiled.adapters.tiff
        - tiled.adapters.utils
        - tiled.adapters.xarray
        - tiled.authenticators
        - tiled.client
        # - tiled.client.sparse
        - tiled.commandline
        - tiled.commandline.main
        - tiled.config
        - tiled.database
        - tiled.database.alembic_utils
        - tiled.database.base
        - tiled.database.core
        - tiled.database.orm
        - tiled.media_type_registration
        - tiled.profiles
        - tiled.queries
        - tiled.query_registration
        - tiled.scopes
        - tiled.serialization.array
        - tiled.serialization.dataframe
        - tiled.serialization.image_serializer_helpers
        - tiled.serialization.node
        - tiled.serialization.xarray
        - tiled.serialization.sparse
        - tiled.server
        - tiled.server.pydantic_sparse
        - tiled.structures
        - tiled.structures.array
        - tiled.structures.dataframe
        - tiled.structures.sparse
        - tiled.utils
      commands:
        - pip check
        - tiled --help
      requires:
        - pip
        - pytest  # [not win]
        # broken build of httpcore package fails pipcheck
        - httpcore !=0.13.3

about:
  home: https://github.com/bluesky/tiled
  summary: Tile-based access to SciPy/PyData data structures over the web in many formats
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielballan
    - gwbischof
    - mrakitin
